### ISSUE TITLE
QUESTION: windows status

### ISSUE THREAD

**Issue by albop** [QuantEcon/rvlib#19]
I remember there was at some point an issue with the Rmath dlls on windows. Is that solved ? Does rvlib work on windows now ?

**Comment by sglyon** [comment]
I don't believe it has been resolved. However, since that time It think the cross compilation options have improved and I bet we could make it happen. 

I had good luck getting a windows dll for another library using https://github.com/dockcross/dockcross

Maybe we give that a shot?

**Comment by knaaptime** [comment]
I can install the package on windows successfully as long as I build it with [mingw](http://mingw-w64.org/doku.php) rather than the MS build tools. I'm still figuring out exactly what the specific hurdles were (i'm neither a windows nor a C native) but i'm pretty sure it required:

- installing mingw from the web (the m2w64-gcc package from conda may mean you dont actually need the full install, im not sure)
- [m2w64-gcc](https://anaconda.org/conda-forge/m2w64-gcc) and libpython from conda-forge
- set [mingw as compiler](https://cython.readthedocs.io/en/latest/src/tutorial/appendix.html) at $ANACONDA_DIR/Lib/distutils/distutils.cfg

having confirmed its possible, i'll try and get that logic wrapped up somewhere to get builds published on pip and conda-forge

**Comment by knaaptime** [comment]
windows builds are now available on conda-forge
